-- This file was generated by VoltDB version 8.3.2 on: 2018-12-09 15:08:16 GMT+00:00.
-- This file represents the current database schema.
-- Use this file as input to reproduce the current database structure in another database instance.
--
-- This file uses the --inlinebatch feature. Batching processes all of the DDL in a single step
-- dramatically reducing the time required to apply the schema compared to processing each
-- command separately.
--
-- If the schema declares Java stored procedures, be sure to load the .jar file
-- with the classes before loading the schema. For example:
--
-- LOAD CLASSES voltdb-procs.jar;
-- FILE ddl.sql;

file -inlinebatch END_OF_BATCH
CREATE TABLE ADMIN (
   ID varchar(255),
   FIRSTNAME varchar(255) NOT NULL,
   LASTNAME varchar(255) NOT NULL,
   EMAIL varchar(255) NOT NULL,
   PASSWORD varchar(255),
   ORGANIZATIONID varchar(255),
   PRIMARY KEY (ID)
);
CREATE INDEX SYS_IDX_10012 ON ADMIN (ORGANIZATIONID);

CREATE TABLE ADMINROLE (
   ID varchar(255),
   ADMINID varchar(255),
   ROLEID varchar(255),
   PRIMARY KEY (ID)
);
CREATE INDEX SYS_IDX_10036 ON ADMINROLE (ADMINID);
CREATE INDEX SYS_IDX_10038 ON ADMINROLE (ROLEID);

CREATE TABLE ORGANIZATION (
   ID varchar(255),
   NAME varchar(255) NOT NULL,
   MASTER tinyint,
   UNIQUE (NAME),
   PRIMARY KEY (ID)
);

CREATE TABLE PERMISSION (
   ID varchar(255),
   ENTITY tinyint NOT NULL,
   OPERATION tinyint NOT NULL,
   ROLEID varchar(255),
   PRIMARY KEY (ID)
);
CREATE INDEX SYS_IDX_10028 ON PERMISSION (ROLEID);

CREATE TABLE PRODUCT (
   ID varchar(255),
   NAME varchar(255) NOT NULL,
   DESCRIPTION varchar(255),
   PRICE float,
   ORGANIZATIONID varchar(255),
   QUANTITY bigint,
   PRIMARY KEY (ID)
);
CREATE INDEX SYS_IDX_10055 ON PRODUCT (ORGANIZATIONID);

CREATE TABLE PRODUCTSHARINGSTATEMENT (
   ID varchar(255),
   SHARINGORGID varchar(255) NOT NULL,
   ACCESSINGORGID varchar(255) NOT NULL,
   QUANTITY bigint,
   PRICE float,
   RELATION tinyint,
   OPERATION tinyint,
   APPROVED tinyint,
   PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
   ID varchar(255),
   NAME varchar(255) NOT NULL,
   ORGANIZATIONID varchar(255),
   PRIMARY KEY (ID)
);
CREATE INDEX SYS_IDX_10022 ON ROLE (ORGANIZATIONID);

END_OF_BATCH